server:
  port: 8080
spring:
  mail:
    host: host.io
    port: 465
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    protocol: smtp
    test-connection: false
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver


kafka:
  username: todo-username
  password: todo-password
  servers: ${KAFKA_SERVER:localhost:9092}
  idempotence: true
  acks: all
  maxInFlightReq: 5
  group-id: hero-consumer
  auto-offset: earliest
  mechanism: PLAIN
  protocol: SASL_PLAINTEXT
  topics:
    data: send_email
